databases:
  - name: todo_db
    databaseName: todo_db
    user: todo_user

services:
  - type: web
    name: todo-list-app
    env: python
    buildCommand: "pip install -r requirements.txt && python init_db.py"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: todo_db
          property: connectionString
